//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsermapConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsermapConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001,
        ///0002,
        ///0003,
        ///0004,
        ///0005,
        ///0006,
        ///0007,
        ///0008,
        ///0009,
        ///000A,
        ///000B,27C7
        ///000C,
        ///000D,
        ///000E,
        ///000F,
        ///0010,
        ///0011,
        ///0012,
        ///0013,
        ///0014,
        ///0015,
        ///0017,
        ///0018,
        ///0019,
        ///001A,
        ///001B,
        ///001C,
        ///001D,
        ///001E,
        ///001F,
        ///0020,
        ///0021,
        ///0022,
        ///0023,
        ///0024,
        ///0025,
        ///0026,
        ///0027,
        ///0028,
        ///0029,
        ///002A,
        ///002B,
        ///002C,
        ///002D,
        ///002E,
        ///002F,
        ///0030,
        ///0031,
        ///0032,
        ///0033,
        ///0034,
        ///0035,
        ///0036,
        ///0037,
        ///0038,
        ///0039,
        ///003A,
        ///003B,
        ///003C,
        ///003D,
        ///003E,
        ///003F,
        ///0040,
        ///0041,
        ///0042,
        ///0043,
        ///0044,
        ///0045,
        ///0046,
        ///0047,
        ///0048,
        ///0049,
        ///004A,
        ///004B,
        ///004C,
        ///004D,
        ///004E,
        ///004F,
        ///0050,
        ///0051,
        ///0052,
        ///0053,
        ///0054,
        ///0055,
        ///0056 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
    }
}
